"""Write the immutable build identity used by a frozen app.

Run this from the release build before PyInstaller, then remove the generated
``smfs_catalog/_build_stamp.py`` after packaging.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import subprocess


def _head() -> str:
    return subprocess.check_output(
        ["git", "rev-parse", "HEAD"], text=True,
        cwd=Path(__file__).resolve().parents[1],
    ).strip()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--commit", help="build commit; defaults to git HEAD")
    args = parser.parse_args()
    out = Path(__file__).resolve().parents[1] / "smfs_catalog" / "_build_stamp.py"
    content = (
        "# Generated by scripts/write_build_stamp.py; do not edit.\n"
        f"BUILD_COMMIT = {(args.commit or _head())!r}\n"
    )
    out.write_text(content, encoding="utf-8")
    print(out)


if __name__ == "__main__":
    main()
